### ISSUE TITLE
Can't hit shift enter to go down a line when adding bullet point.

### ISSUE THREAD

**Issue by MatteCrystal** [tth05/obsidian-completr#13]
With completr on I can't hit `shift + enter` to go down a line. It doesn't need to be giving a suggestion for this to happen. 

I'll quite often hit shift + enter to create a bullet point and then go down 1 line without deleting that bullet point. I can't do this with completr on. Instead, it behaves as if I only hit enter which causes it to delete the bullet point.

**Comment by tth05** [comment]
Ah, I was wondering if `Shift + Enter` makes a difference somewhere. Of course, if you're using `Enter` as the insertion key and the popup is open, it will behave as if you've pressed just `Enter`. I guess this could be circumvented by also allowing the usage of `Ctrl` to bypass the popup.
Fixed in 4945f2585dc21c2cab2bfb0b9ea08cf62f5cf865
