### ISSUE TITLE
How to jump the cursor in latex snipppets?

### ISSUE THREAD

**Issue by quarkquartet** [tth05/obsidian-completr#16]
A very typical example: insert `\frac{}{}`, I would like to move the cursor from the first bracket to the second. In your gif, I found you pressed a certain key and the cursor is directly moved. But I cannot find that key. I pressed the Tab, and nothing happens. I have to manually move the cursor.

**Comment by tth05** [comment]
You should be able to either press `Tab` or `Enter` and `Shift+Enter` while the popup is open. This works fine for me. Are you on the newest version?

**Comment by firinael** [comment]
Hi, I'm using the latest version of the plugin in the latest version of Obsidian, with full default hotkeys, and can't for the life of me use the "jump cursor" feature. Pressing `Enter` with the fraction autocomplete just places the full snippet and my cursor at the end of it.

**Comment by tth05** [comment]
I'm sorry, but I stopped supporting the legacy editor since live preview came out. Supporting both in the same codebase gets really messy and is a lot more work.

**Comment by firinael** [comment]
Ah okay. Could you add that as a disclaimer in the plugin's readme?
________________________________
De: tth05 ***@***.***>
Enviado: Sunday, May 1, 2022 7:30:57 AM
Para: tth05/obsidian-completr ***@***.***>
Cc: firinael ***@***.***>; Comment ***@***.***>
Assunto: Re: [tth05/obsidian-completr] How to jump the cursor in latex snipppets? (Issue #16)


I'm sorry, but I stopped supporting the legacy editor since live preview came out. Supporting both in the same codebase gets really messy and is a lot more work.

**Comment by tth05** [comment]
Sure, maybe one the other plugins will work for you.
