### ISSUE TITLE
Minimum Trigger Length

### ISSUE THREAD

**Issue by brimwats** [tth05/obsidian-completr#5]
I am really enjoying completr so far! I'm wondering if a minimum-length feature could be implemented? i.e. I really only want it to trigger once the word is over 3 characters. The current word-length feature still triggers for 2-3 letter words (it filters the dictionary length)

**Comment by tth05** [comment]
Probably a good idea to add this, although it doesn't really make sense for the LaTeX provider because there are completions like `\in`. Or the LaTeX provider could have a separate setting. What do you think?

**Comment by brimwats** [comment]
I don't use Latex so I don't have strong recommendations but I'm always in favor of more toggles

**Comment by gabrielegiammatteo** [comment]
Hi! I really like completr and I'm using mostly the dictionary provider and the file scanner to autocomplete complex/long words. However, if I write very short words (e.g. `the`, `in`) it is annoying that the popup is triggered immediately when I type the first letter. And also not useful, because it's faster for me to write the whole word than pick it from the popup. So I'm very in favour of implementing a "delayed trigger". It can be triggered by the number of letters (like the opening post proposal) or it could be triggered by time (e.g. show the popup only after 0.5 seconds I'm on the same word). Maybe the latter option could make more sense in the case of Latex

**Comment by tth05** [comment]
Implemented in 94dc9f10aded10cca0b24c7232399daa037566d7. I've left the LaTeX provider untouched for now
