### ISSUE TITLE
[FR] iOS support...

### ISSUE THREAD

**Issue by zanodor** [tth05/obsidian-completr#51]
...would be great.  
... Actually, I managed to run it in Obsidian iOS for one session (by modifying the manifest file) but the next time it did not allow me to enable it again. It was working flawlessly for that one session, though.  
I wonder what allows a non-mobile app to be installed/enabled for one session and not for a second time? It happened with another plugin (Surfing; it didn't access the internet as per required though) before.  

Cheers

**Comment by tth05** [comment]
I'm sorry, but I do not plan on supporting mobile and especially not iOS, because I don't own a device which runs iOS. I also don't know why editing the manifest file doesn't work, but I'd guess there's some code which causes errors when launching Obsidian and therefore Obsidian automatically disables the plugin.
